# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lndgrpc/compiled/price_oracle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#lndgrpc/compiled/price_oracle.proto\x12\x0epriceoraclerpc\"0\n\nFixedPoint\x12\x13\n\x0b\x63oefficient\x18\x01 \x01(\t\x12\r\n\x05scale\x18\x02 \x01(\r\"\x92\x01\n\nAssetRates\x12\x34\n\x10subjectAssetRate\x18\x01 \x01(\x0b\x32\x1a.priceoraclerpc.FixedPoint\x12\x34\n\x10paymentAssetRate\x18\x02 \x01(\x0b\x32\x1a.priceoraclerpc.FixedPoint\x12\x18\n\x10\x65xpiry_timestamp\x18\x03 \x01(\x04\"p\n\x0e\x41ssetSpecifier\x12\x12\n\x08\x61sset_id\x18\x01 \x01(\x0cH\x00\x12\x16\n\x0c\x61sset_id_str\x18\x02 \x01(\tH\x00\x12\x13\n\tgroup_key\x18\x03 \x01(\x0cH\x00\x12\x17\n\rgroup_key_str\x18\x04 \x01(\tH\x00\x42\x04\n\x02id\"\xbb\x02\n\x16QueryAssetRatesRequest\x12\x39\n\x10transaction_type\x18\x01 \x01(\x0e\x32\x1f.priceoraclerpc.TransactionType\x12\x35\n\rsubject_asset\x18\x02 \x01(\x0b\x32\x1e.priceoraclerpc.AssetSpecifier\x12 \n\x18subject_asset_max_amount\x18\x03 \x01(\x04\x12\x35\n\rpayment_asset\x18\x04 \x01(\x0b\x32\x1e.priceoraclerpc.AssetSpecifier\x12 \n\x18payment_asset_max_amount\x18\x05 \x01(\x04\x12\x34\n\x10\x61sset_rates_hint\x18\x06 \x01(\x0b\x32\x1a.priceoraclerpc.AssetRates\"L\n\x19QueryAssetRatesOkResponse\x12/\n\x0b\x61sset_rates\x18\x01 \x01(\x0b\x32\x1a.priceoraclerpc.AssetRates\";\n\x1aQueryAssetRatesErrResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\r\"\x99\x01\n\x17QueryAssetRatesResponse\x12\x37\n\x02ok\x18\x01 \x01(\x0b\x32).priceoraclerpc.QueryAssetRatesOkResponseH\x00\x12;\n\x05\x65rror\x18\x02 \x01(\x0b\x32*.priceoraclerpc.QueryAssetRatesErrResponseH\x00\x42\x08\n\x06result*)\n\x0fTransactionType\x12\x0c\n\x08PURCHASE\x10\x00\x12\x08\n\x04SALE\x10\x01\x32q\n\x0bPriceOracle\x12\x62\n\x0fQueryAssetRates\x12&.priceoraclerpc.QueryAssetRatesRequest\x1a\'.priceoraclerpc.QueryAssetRatesResponseB?Z=github.com/lightninglabs/taproot-assets/taprpc/priceoraclerpcb\x06proto3')

_TRANSACTIONTYPE = DESCRIPTOR.enum_types_by_name['TransactionType']
TransactionType = enum_type_wrapper.EnumTypeWrapper(_TRANSACTIONTYPE)
PURCHASE = 0
SALE = 1


_FIXEDPOINT = DESCRIPTOR.message_types_by_name['FixedPoint']
_ASSETRATES = DESCRIPTOR.message_types_by_name['AssetRates']
_ASSETSPECIFIER = DESCRIPTOR.message_types_by_name['AssetSpecifier']
_QUERYASSETRATESREQUEST = DESCRIPTOR.message_types_by_name['QueryAssetRatesRequest']
_QUERYASSETRATESOKRESPONSE = DESCRIPTOR.message_types_by_name['QueryAssetRatesOkResponse']
_QUERYASSETRATESERRRESPONSE = DESCRIPTOR.message_types_by_name['QueryAssetRatesErrResponse']
_QUERYASSETRATESRESPONSE = DESCRIPTOR.message_types_by_name['QueryAssetRatesResponse']
FixedPoint = _reflection.GeneratedProtocolMessageType('FixedPoint', (_message.Message,), {
  'DESCRIPTOR' : _FIXEDPOINT,
  '__module__' : 'lndgrpc.compiled.price_oracle_pb2'
  # @@protoc_insertion_point(class_scope:priceoraclerpc.FixedPoint)
  })
_sym_db.RegisterMessage(FixedPoint)

AssetRates = _reflection.GeneratedProtocolMessageType('AssetRates', (_message.Message,), {
  'DESCRIPTOR' : _ASSETRATES,
  '__module__' : 'lndgrpc.compiled.price_oracle_pb2'
  # @@protoc_insertion_point(class_scope:priceoraclerpc.AssetRates)
  })
_sym_db.RegisterMessage(AssetRates)

AssetSpecifier = _reflection.GeneratedProtocolMessageType('AssetSpecifier', (_message.Message,), {
  'DESCRIPTOR' : _ASSETSPECIFIER,
  '__module__' : 'lndgrpc.compiled.price_oracle_pb2'
  # @@protoc_insertion_point(class_scope:priceoraclerpc.AssetSpecifier)
  })
_sym_db.RegisterMessage(AssetSpecifier)

QueryAssetRatesRequest = _reflection.GeneratedProtocolMessageType('QueryAssetRatesRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYASSETRATESREQUEST,
  '__module__' : 'lndgrpc.compiled.price_oracle_pb2'
  # @@protoc_insertion_point(class_scope:priceoraclerpc.QueryAssetRatesRequest)
  })
_sym_db.RegisterMessage(QueryAssetRatesRequest)

QueryAssetRatesOkResponse = _reflection.GeneratedProtocolMessageType('QueryAssetRatesOkResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYASSETRATESOKRESPONSE,
  '__module__' : 'lndgrpc.compiled.price_oracle_pb2'
  # @@protoc_insertion_point(class_scope:priceoraclerpc.QueryAssetRatesOkResponse)
  })
_sym_db.RegisterMessage(QueryAssetRatesOkResponse)

QueryAssetRatesErrResponse = _reflection.GeneratedProtocolMessageType('QueryAssetRatesErrResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYASSETRATESERRRESPONSE,
  '__module__' : 'lndgrpc.compiled.price_oracle_pb2'
  # @@protoc_insertion_point(class_scope:priceoraclerpc.QueryAssetRatesErrResponse)
  })
_sym_db.RegisterMessage(QueryAssetRatesErrResponse)

QueryAssetRatesResponse = _reflection.GeneratedProtocolMessageType('QueryAssetRatesResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYASSETRATESRESPONSE,
  '__module__' : 'lndgrpc.compiled.price_oracle_pb2'
  # @@protoc_insertion_point(class_scope:priceoraclerpc.QueryAssetRatesResponse)
  })
_sym_db.RegisterMessage(QueryAssetRatesResponse)

_PRICEORACLE = DESCRIPTOR.services_by_name['PriceOracle']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z=github.com/lightninglabs/taproot-assets/taprpc/priceoraclerpc'
  _TRANSACTIONTYPE._serialized_start=981
  _TRANSACTIONTYPE._serialized_end=1022
  _FIXEDPOINT._serialized_start=55
  _FIXEDPOINT._serialized_end=103
  _ASSETRATES._serialized_start=106
  _ASSETRATES._serialized_end=252
  _ASSETSPECIFIER._serialized_start=254
  _ASSETSPECIFIER._serialized_end=366
  _QUERYASSETRATESREQUEST._serialized_start=369
  _QUERYASSETRATESREQUEST._serialized_end=684
  _QUERYASSETRATESOKRESPONSE._serialized_start=686
  _QUERYASSETRATESOKRESPONSE._serialized_end=762
  _QUERYASSETRATESERRRESPONSE._serialized_start=764
  _QUERYASSETRATESERRRESPONSE._serialized_end=823
  _QUERYASSETRATESRESPONSE._serialized_start=826
  _QUERYASSETRATESRESPONSE._serialized_end=979
  _PRICEORACLE._serialized_start=1024
  _PRICEORACLE._serialized_end=1137
# @@protoc_insertion_point(module_scope)
