# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lndgrpc/compiled/tapcommon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n lndgrpc/compiled/tapcommon.proto\x12\x06taprpc\".\n\x08OutPoint\x12\x0c\n\x04txid\x18\x01 \x01(\x0c\x12\x14\n\x0coutput_index\x18\x02 \x01(\rB0Z.github.com/lightninglabs/taproot-assets/taprpcb\x06proto3')



_OUTPOINT = DESCRIPTOR.message_types_by_name['OutPoint']
OutPoint = _reflection.GeneratedProtocolMessageType('OutPoint', (_message.Message,), {
  'DESCRIPTOR' : _OUTPOINT,
  '__module__' : 'lndgrpc.compiled.tapcommon_pb2'
  # @@protoc_insertion_point(class_scope:taprpc.OutPoint)
  })
_sym_db.RegisterMessage(OutPoint)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z.github.com/lightninglabs/taproot-assets/taprpc'
  _OUTPOINT._serialized_start=44
  _OUTPOINT._serialized_end=90
# @@protoc_insertion_point(module_scope)
